Move rds backup library from customer-service-monitoring
opentelekomcloud-infra/csm-test-utils pull request #40
Opened 2021-01-27 07:36 UTC by Polina-Gubina

Move rds backup library from customer-service-monitoring

2021-01-27 09:07 UTC, outcatcher requested changes

2021-01-27 13:18 UTC, outcatcher commented
recheck

2021-01-27 13:23 UTC, outcatcher commented
recheck

2021-01-28 12:48 UTC, anton-sidelnikov approved these changes

2021-01-28 12:49 UTC, outcatcher commented
recheck

2021-01-28 13:08 UTC, outcatcher commented on csm_test_utils/rds_backup/generation/pg2/db_methods.py
> +        return res
Please get rid of `try...` blocks, as per discussion

2021-01-29 11:14 UTC, outcatcher requested changes

2021-01-29 11:14 UTC, outcatcher commented on tests/unit/test_rds.py
> +    with open(file_name, 'r') as read_obj:
Why `read_obj` is named like that? Maybe name it `lines` or `file`?

2021-01-29 11:14 UTC, outcatcher commented on tests/unit/test_rds.py
> +        assert check_if_string_in_file(LOG_PATH, LOG_STRING_COMMIT)
As `unittest` is used, `self.Assert...` methods should be used instead of `assert`

2021-01-29 11:14 UTC, outcatcher commented on csm_test_utils/rds_backup/generation/pg2/db_methods.py
> +            logging.info('Commit session')
`Commit session` will be written each iteration

2021-01-29 11:14 UTC, outcatcher commented on tests/unit/test_rds.py
> +        assert check_if_string_in_file(LOG_PATH, LOG_STRING_COMMIT)
It's better to actually check DB size to be `data['max_size_in_bytes']`

2021-01-29 11:30 UTC, anton-sidelnikov requested changes

2021-01-29 11:30 UTC, anton-sidelnikov commented on csm_test_utils/__main__.py
> +from csm_test_utils.rds_backup import backup_status, generation
backup_status not used here

2021-01-29 11:30 UTC, anton-sidelnikov commented on csm_test_utils/rds_backup/backup_check/rds_backup.py
> +import datetime
multiple import

2021-01-29 11:30 UTC, anton-sidelnikov commented on csm_test_utils/rds_backup/backup_check/rds_backup.py
> +    }
i think it's good idea to store that struct in separate .yaml file

2021-01-29 14:19 UTC, Polina-Gubina commented on csm_test_utils/rds_backup/backup_check/rds_backup.py
> +import datetime
done

2021-02-01 07:37 UTC, Polina-Gubina commented
recheck

2021-02-01 07:45 UTC, outcatcher commented
recheck

2021-02-01 07:50 UTC, outcatcher commented
recheck

2021-02-01 08:09 UTC, outcatcher commented
recheck

2021-02-01 08:50 UTC, outcatcher commented
recheck

2021-02-01 09:00 UTC, outcatcher commented
recheck

2021-02-01 09:06 UTC, outcatcher commented
recheck

2021-02-01 09:17 UTC, outcatcher commented
recheck

2021-02-01 10:02 UTC, Polina-Gubina commented
recheck

2021-02-01 13:58 UTC, outcatcher commented
recheck

2021-02-01 15:34 UTC, Polina-Gubina commented
recheck

2021-02-02 12:08 UTC, anton-sidelnikov approved these changes

2021-02-02 13:13 UTC, anton-sidelnikov approved these changes

2021-02-02 14:07 UTC, outcatcher approved these changes

2021-02-02 14:11 UTC, lego963 approved these changes

2021-02-02 14:29 UTC, outcatcher commented
regate

2021-02-02 14:29 UTC, Polina-Gubina commented
regate

2021-02-02 14:31 UTC, outcatcher commented
recheck

2021-02-02 14:38 UTC, merged